server:
  port: 8080
  address: 0.0.0.0
logging:
  config: classpath:log4j2-local.yml
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  main:
    banner-mode: console
  
  redis:
    host: localhost
    port: 6379
    password: 1234
    
  cache:
    type: redis
    redis:
      time-to-live: 3600 
      cache-null-values: true
  
  #H2 Setting Info
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
      
  #DataBase Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: hch
    password: hch123
    
  #Jpa Setting Info
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:  
      hibernate:  
        format_sql: true
    
env: "local"